//
// EditorSchemeGenerator.cs
//
// Copyright (c) 2026 Jeremy Ellis and contributors
// SPDX-License-Identifier: MIT
//

using System.Text;

namespace CodeBrix.Develop.Ide.Themes;

/// <summary>
/// Translates a VS Code theme's editor colors and TextMate token rules
/// into a GtkSourceView 5 style-scheme XML document, mapping the common
/// TextMate scopes onto GtkSourceView's def:* styles (which the bundled
/// language definitions — C#, XML, and friends — all inherit from).
/// </summary>
static class EditorSchemeGenerator
{
    // GtkSourceView style name → TextMate candidate scopes, best first.
    static readonly (string Style, string[] Scopes)[] tokenStyleMap =
    {
        ("def:comment", new[] { "comment" }),
        ("def:doc-comment", new[] { "comment.block.documentation", "comment" }),
        ("def:doc-comment-element", new[] { "comment.block.documentation", "comment" }),
        ("def:shebang", new[] { "comment" }),
        ("def:string", new[] { "string" }),
        ("def:character", new[] { "constant.character", "string" }),
        ("def:special-char", new[] { "constant.character.escape" }),
        ("def:number", new[] { "constant.numeric" }),
        ("def:decimal", new[] { "constant.numeric" }),
        ("def:floating-point", new[] { "constant.numeric" }),
        ("def:base-n-integer", new[] { "constant.numeric" }),
        ("def:complex", new[] { "constant.numeric" }),
        ("def:boolean", new[] { "constant.language.boolean", "constant.language" }),
        ("def:special-constant", new[] { "constant.language" }),
        ("def:constant", new[] { "constant.other", "constant.language", "variable.other.constant" }),
        ("def:keyword", new[] { "keyword", "storage.type" }),
        ("def:statement", new[] { "keyword.control", "keyword" }),
        ("def:operator", new[] { "keyword.operator" }),
        ("def:type", new[] { "entity.name.type", "entity.name.class", "support.type", "support.class", "storage.type" }),
        ("def:builtin", new[] { "support.class", "support.type", "constant.language" }),
        ("def:function", new[] { "entity.name.function", "support.function" }),
        ("def:identifier", new[] { "variable", "entity.name.variable" }),
        ("def:preprocessor", new[] { "meta.preprocessor", "keyword.control.directive", "keyword.preprocessor" }),
        ("def:error", new[] { "invalid.illegal", "invalid" }),
        ("def:warning", new[] { "invalid.deprecated" }),
        ("def:link-destination", new[] { "markup.underline.link", "string" }),
    };

    /// <summary>Generates the style-scheme XML document for the given theme.</summary>
    public static string Generate(VSCodeTheme theme)
    {
        var dark = theme.Info.IsDark;
        string Col(string darkFallback, string lightFallback, params string[] keys) =>
            theme.GetColor(dark ? darkFallback : lightFallback, keys);

        var editorBg = Col("#1E1E1E", "#FFFFFF", "editor.background");
        var editorFg = VSCodeTheme.NormalizeColor(theme.DefaultTokenForeground)
            ?? Col("#D4D4D4", "#000000", "editor.foreground", "foreground");
        var selectionBg = Col("#264F78", "#ADD6FF", "editor.selectionBackground");
        var lineHighlight = Col("rgba(255, 255, 255, 0.04)", "rgba(0, 0, 0, 0.04)",
            "editor.lineHighlightBackground");
        var lineNumberFg = Col("#858585", "#237893", "editorLineNumber.foreground");
        var activeLineNumberFg = Col("#C6C6C6", "#0B216F", "editorLineNumber.activeForeground", "editorLineNumber.foreground");
        var cursorFg = Col("#AEAFAD", "#000000", "editorCursor.foreground");
        var bracketMatchBg = Col("rgba(0, 100, 100, 0.35)", "rgba(0, 100, 200, 0.2)", "editorBracketMatch.background");
        var searchMatchBg = Col("#623315", "#A8AC94", "editor.findMatchHighlightBackground", "editor.findMatchBackground");

        var xml = new StringBuilder();
        xml.AppendLine("""<?xml version="1.0" encoding="UTF-8"?>""");
        xml.AppendLine("<!-- Generated by CodeBrix.Develop from the embedded VS Code theme");
        xml.AppendLine($"     '{theme.Info.Name}' (see THIRD-PARTY-NOTICES.txt). Regenerated on");
        xml.AppendLine("     every application start; do not edit. -->");
        xml.AppendLine($"""<style-scheme id="{theme.Info.EditorSchemeId}" name="{Escape(theme.Info.Name)}" version="1.0">""");
        xml.AppendLine($"""  <style name="text" foreground="{editorFg}" background="{editorBg}"/>""");
        xml.AppendLine($"""  <style name="selection" background="{selectionBg}"/>""");
        xml.AppendLine($"""  <style name="current-line" background="{lineHighlight}"/>""");
        xml.AppendLine($"""  <style name="line-numbers" foreground="{lineNumberFg}" background="{editorBg}"/>""");
        xml.AppendLine($"""  <style name="current-line-number" foreground="{activeLineNumberFg}" background="{lineHighlight}"/>""");
        xml.AppendLine($"""  <style name="cursor" foreground="{cursorFg}"/>""");
        xml.AppendLine($"""  <style name="bracket-match" background="{bracketMatchBg}" bold="true"/>""");
        xml.AppendLine($"""  <style name="search-match" background="{searchMatchBg}"/>""");

        foreach (var (style, scopes) in tokenStyleMap)
        {
            var token = theme.MatchToken(scopes);
            if (token == null)
                continue;
            var attributes = new StringBuilder();
            if (token.Foreground != null)
                attributes.Append($""" foreground="{token.Foreground}" """.TrimEnd());
            if (token.Bold)
                attributes.Append(""" bold="true" """.TrimEnd());
            if (token.Italic)
                attributes.Append(""" italic="true" """.TrimEnd());
            if (token.Underline)
                attributes.Append(""" underline="single" """.TrimEnd());
            if (attributes.Length > 0)
                xml.AppendLine($"""  <style name="{style}"{attributes}/>""");
        }

        xml.AppendLine("</style-scheme>");
        return xml.ToString();
    }

    static string Escape(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");
}
