//
// FrameBufferHeadSwap.cs
//
// Copyright (c) 2026 Jeremy Ellis and contributors
// SPDX-License-Identifier: MIT
//

using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace CodeBrix.Develop.Core.Projects;

/// <summary>
/// The silent head swap behind the frame-buffer emulator: when a
/// .LinuxFrameBuffer head is run or debugged, the IDE builds it against the
/// EMULATED head package instead of the real one — without ever opening the
/// user's csproj for writing.
/// <para>
/// The mechanism is an MSBuild targets file generated into the IDE's own temp
/// area and injected with -p:CustomAfterMicrosoftCommonTargets=&lt;file&gt;, so it
/// evaluates AFTER the csproj body: a PackageReference Remove of the real
/// FrameBuffer package plus an Include of the Emulated one, guarded by a
/// condition on the head project's name (the property flows to every project
/// in the graph; the guard keeps the swap out of .Core and the rest). NuGet
/// restore honors items added this way, and the next plain build — no property
/// — re-restores the original graph automatically. Nothing to swap back,
/// nothing to repair after a crash, and git stays clean at every instant.
/// </para>
/// </summary>
public static class FrameBufferHeadSwap
{
    /// <summary>The real FrameBuffer head package, removed by the swap.</summary>
    public const string FrameBufferPackageId = "CodeBrix.Platform.Runtime.Skia.FrameBuffer.ApacheLicenseForever";

    /// <summary>The emulated head package, swapped in for emulator builds.</summary>
    public const string EmulatedPackageId = "CodeBrix.Platform.Runtime.Skia.FrameBuffer.Emulated.ApacheLicenseForever";

    /// <summary>
    /// Whether the head project can be swapped at all: it must reference the
    /// FrameBuffer head package (from-source ProjectReference consumers are
    /// not supported — real applications always reference the package).
    /// </summary>
    public static bool CanSwap(DotNetProject headProject)
        => headProject.HasPackageReference(FrameBufferPackageId);

    /// <summary>
    /// Generates the swap targets file for one head project and returns the
    /// MSBuild argument to build with. The file pins the Emulated package to
    /// the same version the project pinned the real one to (the family always
    /// publishes both at one version), and chain-imports the project's own
    /// CustomAfterMicrosoftCommonTargets value so the -p: override does not
    /// mask it.
    /// </summary>
    public static async Task<string> CreateSwapArgumentAsync(DotNetProject headProject, CancellationToken cancellationToken = default)
    {
        // The -p: global property overrides any project-set value, so read
        // what the project evaluates WITHOUT the override and import it from
        // the generated file. (MSBuild's own default for this property points
        // at a Custom.After.Microsoft.Common.targets that rarely exists; the
        // Exists guard makes chaining it a no-op.)
        var prior = string.Empty;
        try
        {
            var properties = await headProject.EvaluatePropertiesAsync(
                "Debug", cancellationToken, "CustomAfterMicrosoftCommonTargets").ConfigureAwait(false);
            properties.TryGetValue("CustomAfterMicrosoftCommonTargets", out prior);
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            LoggingService.LogWarning($"Could not evaluate CustomAfterMicrosoftCommonTargets for {headProject.Name}; not chaining. {ex.Message}");
        }

        var version = headProject.PackageReferences
            .FirstOrDefault(reference => string.Equals(reference.Id, FrameBufferPackageId, StringComparison.OrdinalIgnoreCase))
            ?.Version;

        var include = new XElement("PackageReference", new XAttribute("Include", EmulatedPackageId));
        if (!string.IsNullOrEmpty(version))
            include.Add(new XAttribute("Version", version));

        var root = new XElement("Project",
            new XComment(" Generated by CodeBrix.Develop for a frame-buffer emulator launch. "
                + "Injected via -p:CustomAfterMicrosoftCommonTargets; user project files are never modified. "),
            new XElement("ItemGroup",
                new XAttribute("Condition", $"'$(MSBuildProjectName)' == '{headProject.Name}'"),
                new XElement("PackageReference", new XAttribute("Remove", FrameBufferPackageId)),
                include));
        if (!string.IsNullOrWhiteSpace(prior) && !prior.Contains('\''))
        {
            root.AddFirst(new XElement("Import",
                new XAttribute("Project", prior),
                new XAttribute("Condition", $"Exists('{prior}')")));
        }

        var directory = Path.Combine(Path.GetTempPath(), "CodeBrix.Develop", "fbemu-swap");
        Directory.CreateDirectory(directory);
        var path = Path.Combine(directory, headProject.Name + ".targets");
        new XDocument(root).Save(path);
        return $"-p:CustomAfterMicrosoftCommonTargets={path}";
    }
}
